# Generated by Django 5.0.2 on 2024-05-26 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='details',
            new_name='detail',
        ),
    ]
