# Generated by Django 5.0.2 on 2024-06-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_details_service_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media')),
                ('alt_text', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
