# Generated by Django 5.0.2 on 2024-06-04 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_banners_delete_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banners',
        ),
    ]
