# Generated by Django 5.0.2 on 2024-06-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0004_delete_banners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bannners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='banners')),
                ('alt_text', models.CharField(max_length=100)),
            ],
        ),
    ]
