# Generated by Django 5.0.2 on 2024-06-21 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bannners',
            new_name='Banners',
        ),
    ]
