# Generated by Django 5.0.2 on 2024-08-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_enquiry_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.CharField(max_length=20),
        ),
    ]
