# Generated by Django 5.0.2 on 2024-08-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_subscriptionplans_subscriptionplansfeatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplans',
            name='highlight_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
