# Generated by Django 5.0.2 on 2024-08-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_subscriptionplans_highlight_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplansfeatures',
            name='subplan',
        ),
        migrations.AddField(
            model_name='subscriptionplansfeatures',
            name='subplan',
            field=models.ManyToManyField(to='main.subscriptionplans'),
        ),
    ]
