# Generated by Django 5.0.2 on 2024-08-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_subscriptionplansfeatures_subplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplans',
            name='max_members',
            field=models.IntegerField(null=True),
        ),
    ]
