# Generated by Django 5.0.2 on 2024-08-22 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_subscriptionplansdiscount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionPlansDiscount',
        ),
    ]
