# Generated by Django 5.0.2 on 2024-08-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
