# Generated by Django 5.0.2 on 2024-08-29 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_notify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='status',
        ),
    ]
