# Generated by Django 5.0.2 on 2024-08-31 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_assignsubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignsubscriber',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subscriptiontype'),
        ),
    ]
