# Generated by Django 5.0.2 on 2024-09-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_assignsubscriber_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplans',
            name='validity',
            field=models.IntegerField(null=True),
        ),
    ]
