# Generated by Django 5.0.2 on 2024-09-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_subscriptionplans_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='reg_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
