# Generated by Django 5.0.2 on 2024-09-04 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_banners_options_alter_galleryimages_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerAcheivements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_awarded', models.DateField()),
                ('description', models.TextField(blank=True, max_length=300)),
                ('badge_image', models.ImageField(blank=True, upload_to='achievement_badges/')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.trainer')),
            ],
        ),
    ]
