# Generated by Django 5.0.2 on 2024-09-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_traineracheivements'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='month_salary',
            field=models.IntegerField(null=True),
        ),
    ]
