# Generated by Django 5.0.2 on 2024-09-07 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_trainermessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainermessage',
            name='user_type',
        ),
    ]
