# Generated by Django 5.0.2 on 2024-09-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_remove_trainermessage_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainernotification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
