# Generated by Django 5.0.2 on 2024-09-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_trainersubscriberreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(upload_to='main_logo/')),
            ],
        ),
    ]
