# Generated by Django 5.0.2 on 2024-09-21 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_mainlogo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
