# Generated by Django 5.0.2 on 2024-09-23 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_delete_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainermessage',
            options={},
        ),
        migrations.RenameField(
            model_name='trainermessage',
            old_name='user',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='trainermessage',
            name='trainer',
        ),
        migrations.AddField(
            model_name='trainermessage',
            name='assign_subscriber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.assignsubscriber'),
        ),
        migrations.AddField(
            model_name='trainermessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
