# Generated by Django 5.0.2 on 2024-09-23 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_trainermessage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainermessage',
            options={'verbose_name_plural': 'Messages to Trainers'},
        ),
        migrations.RemoveField(
            model_name='trainermessage',
            name='assign_subscriber',
        ),
        migrations.RemoveField(
            model_name='trainermessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='trainermessage',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='trainermessage',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.trainer'),
        ),
        migrations.AddField(
            model_name='trainermessage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
