# Generated by Django 5.0.2 on 2024-09-29 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_trainermessage_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainerMessage',
        ),
    ]
